#!/bin/bash


#######################################
# FUNCTIONS
#######################################

# Create .env from .env.example
env () {
    if [ ! -f app/.env ]; then
        cp app/.env.example app/.env
    fi
}

# Initialise the Docker environment and AWS VPC
init () {
    env #\
        #&& ./vpc-init # TODO: Ensure this script works
}

# Destroy the EC2 instance
destroy () {
    vagrant destroy
    read -p "    Are you sure you want to destroy the RDS database? [y/N]: " -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit; fi
    ./rds-destroy
}

# Start the EC2 and RDS instances
up () {
    ./rds-init \
        && vagrant up --provider=aws
}


#######################################
# MENU
#######################################

case "$1" in
    init)
        init
        ;;
    destroy)
        destroy
        ;;
    up)
        up
        ;;
    *)
        cat << EOF

Command line helper program for deploying QuickREG to AWS.

Usage:
    quickreg <command>

Available commands:
    init ...................................... Configure an AWS VPC and docker enviornment
    up ........................................ Start an EC2 and RDS instance along with docker containers
    destroy ................................... Stop the EC2 instance along with the docker containers

EOF
        exit 1
        ;;
esac
