version: '3'

services:

  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./src:/var/www/php:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - phpmyadmindata:/usr/src/phpmyadmin:ro
    depends_on:
      - php
      - phpmyadmin

  php:
    build: ./.docker/php
    restart: always
    environment:
      - DB_HOST=${RDS_ENDPOINT}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    restart: always
    environment:
      - PMA_HOST=${RDS_ENDPOINT}
    volumes:
      - phpmyadmindata:/usr/src/phpmyadmin

volumes:

  mysql-data:

  phpmyadmindata:

# vim: ts=2 sw=2 et
